# Generated by Django 5.2.7 on 2025-11-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_name_en_category_name_ky_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_ru',
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name (EN)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ky',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Аталышы (KY)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name (EN)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ky',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Аталышы (KY)'),
        ),
    ]
